local_repository(
	name = "repo_rule",
	path = "../../repo_rule_prototype"
)

load("@repo_rule//:repo_rule.bzl", "rule_collector_rule")

rule_collector_rule(
	name = "foo",
	# direct_deps_file = "//:input.txt"
)

load("@foo//:repositories.bzl", "maven_repositories")
maven_repositories()

# load("@repo_rule//:repositories.bzl", "maven_repositories")
# maven_repositories()


# load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")


# jvm_maven_import_external(
#     name = "truth",
#     artifact = "com.google.truth:truth:0.30",
#     artifact_sha256 = "f4a4c5e69c4994b750ce3ee80adbb2b7150fe39f057d7dff89832c8ca3af512e",
#     server_urls = ["http://central.maven.org/maven2"],
#     licenses = ["notice"],  # Apache 2.0
#     rule_name = "java_import"
# )