local_repository(
	name = "repo_rule",
	path = "../rule_definition"
)

load("@repo_rule//:repo_rule.bzl", "rule_collector_rule")

rule_collector_rule(
	name = "foo",
	# direct_deps_file = "//:input.txt"
)

load("@foo//:repositories.bzl", "maven_repositories")
maven_repositories()
